Feature/milestone2
jessicafarias/calculator-react pull request #2
Opened 2021-01-17 01:49 UTC by jessicafarias

**This is the second milestone of the calculator project.**

-  In this second milestone I'm Adding 4 components (App, Display, Button and ButtonPanel)

Thanks for review.

2021-01-17 09:03 UTC, Forison requested changes
## Status::Changes Required❌

# 👋 @jessicafarias,
  
#### Good job done on this one so far, however, there are a few issues to address to get this project approved.
 
- App Component 

* [ ] App.jsx  has children components wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))

- Display Component

* [ ] its result prop should be a String with default value = '0' ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)) ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)). currently typeOf result would return number instead of string.

- check my comments below👇
#### That is it kindly make the changes and submit a re-review👷.
#### Happy coding👨‍💻
Addo Forison

2021-01-17 09:03 UTC, Forison commented on src/components/App.js
> +      <div>
- Use a fragment in other to create an efficient render and no creation of extra node. `<></>`

2021-01-17 09:03 UTC, Forison commented on src/components/Button.js
> +const Button = props => {
**[optional]**
we can equally destructure at the argument level like this `const Button = ({name}) => {`

2021-01-17 09:03 UTC, Forison commented on src/components/Display.js
> +  result: 0,
Change the result value to string
result: '0'

2021-01-17 09:03 UTC, Forison commented on src/components/ButtonPanel.js
> +    <div>
**[OPTIONAL]**
You could store the button name list in an array, loop over the array containing the button names and render button each time you loop over the button name array, it is much more cleaner than what we have now.

2021-01-18 17:04 UTC, jessicafarias commented
Thanks alot for this helpful review.

2021-01-18 17:12 UTC, rOluochKe approved these changes
Hello @jessicafarias 
### Good work in making the changes, the project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2021-01-18 17:16 UTC, merged